// examples/stackblitz-solid/src/main.jsx
// Signup form demo: schema-defined validators, cross-field password check,
// draft persistence (reload the page mid-typing), undo/redo history, a
// cancellable server-side username check and a simulated server error on
// submit. The devtools panel at the bottom shows the live engine state;
// sensitive fields (password) are masked automatically.
//
// Unlike the React/Preact examples, field handles are read directly as
// accessors inside JSX (`handle.value()`) — Solid's compiler wraps each
// such binding in its own fine-grained update, so there is no
// useMdyField-style hook or whole-component re-render here at all.
import "@modyra/styles/material.css";
import { render } from "solid-js/web";
import { onMount } from "solid-js";
import {
  createSolidForm, crossField, email, field, minLength, required,
  serverValidator,
} from "@modyra/solid";
import { mountMdyDevtools } from "@modyra/core/devtools";

// Simulated availability endpoint. The abort signal cancels the request
// when a newer keystroke supersedes the run (last-wins), so stale replies
// never land on the field.
const isUsernameTaken = (value, signal) =>
  new Promise((resolve, reject) => {
    const timer = setTimeout(() => resolve(["admin", "root"].includes(value)), 350);
    signal?.addEventListener("abort", () => {
      clearTimeout(timer);
      reject(new DOMException("aborted", "AbortError"));
    });
  });

function TextField(props) {
  const { label, handle, type = "text" } = props;
  return (
    <div class={`mdy-renderer mdy-renderer--text${handle.touched() ? " mdy-renderer--touched" : ""}`}>
      <label class="mdy-label">
        {label}
        {/* required() marks the field, so the star and aria stay in sync */}
        {handle.required() && <span class="mdy-label__required" aria-hidden="true">*</span>}
      </label>
      <div class="mdy-input-wrapper">
        <input
          type={type}
          value={handle.value() ?? ""}
          aria-invalid={!handle.valid()}
          aria-required={handle.required()}
          onInput={(e) => handle.set(e.target.value)}
          onBlur={handle.markAsTouched}
        />
      </div>
      {/* Async validators keep the field pending until the run settles */}
      {handle.pending() && (
        <div class="mdy-supporting-text" role="status">checking…</div>
      )}
      {handle.touched() && handle.errors().length > 0 && (
        <ul class="mdy-control__errors" role="alert">
          {handle.errors().map((er) => <li class="mdy-control__error">{er.message}</li>)}
        </ul>
      )}
    </div>
  );
}

function Signup() {
  const form = createSolidForm(
    {
      // Debounced, cancellable availability check with a 2s timeout —
      // try "admin" or "root".
      username: field(
        "",
        [required(), minLength(3)],
        serverValidator(
          async (value, { signal }) =>
            (await isUsernameTaken(value, signal)) ? "Username is already taken" : null,
          { debounceMs: 300, timeoutMs: 2000 },
        ),
      ),
      name: field("", [required(), minLength(2)]),
      email: field("", [required(), email()]),
      password: field("", [required(), minLength(8)]),
      confirm: field("", [required()]),
    },
    {
      // Cross-field rules see the whole typed value and attribute their
      // error to the involved fields.
      validators: [
        crossField(["confirm"], (v) =>
          v.password === v.confirm ? null : "Passwords do not match"),
      ],
      // Value snapshots for undo/redo; keystrokes are batched.
      history: { debounceMs: 300 },
      // Autosaved to localStorage, restored on reload, cleared on submit.
      // The password never touches storage.
      draft: { key: "signup-stackblitz-solid", exclude: ["password", "confirm"] },
    },
  );

  let devtools;
  onMount(() => mountMdyDevtools(form, devtools));

  const submit = (e) => {
    e.preventDefault();
    void form.submit(async (value) => {
      // Returned errors are shown on the matching fields until edited.
      if (value.email === "taken@example.com") {
        return [{ path: "email", kind: "server", message: "This email is already registered" }];
      }
      console.log("submitted", value);
    });
  };

  return (
    <main style={{ "max-width": "30rem", margin: "2rem auto", display: "grid", gap: "1rem" }}>
      <h1>Modyra × Solid</h1>
      <p>Try username <code>admin</code> for a cancellable server check, <code>taken@example.com</code> for a server error. Reload mid-typing: the draft survives.</p>
      <form class="mdy-form" onSubmit={submit}>
        <TextField label="Username" handle={form.f.username} />
        <TextField label="Name" handle={form.f.name} />
        <TextField label="Email" handle={form.f.email} type="email" />
        <TextField label="Password" handle={form.f.password} type="password" />
        <TextField label="Confirm password" handle={form.f.confirm} type="password" />
        <div style={{ display: "flex", gap: ".5rem" }}>
          <button type="submit" disabled={!form.state.canSubmit()}>Sign up</button>
          <button type="button" disabled={!form.canUndo()} onClick={() => form.undo()}>Undo</button>
          <button type="button" disabled={!form.canRedo()} onClick={() => form.redo()}>Redo</button>
        </div>
      </form>
      <div ref={devtools}></div>
    </main>
  );
}
render(() => <Signup />, document.getElementById("app"));

// examples/stackblitz-lit/src/main.js
// Signup form demo: schema-defined validators, cross-field password check,
// draft persistence (reload the page mid-typing), undo/redo history, a
// cancellable server-side username check and a simulated server error on
// submit. <mdy-text-field> renders in light DOM, so the theme stylesheet
// applies to its markup directly. A second "control catalog" form below
// exercises every widget the UI package ships.
import "@modyra/styles/material.css";
import {
  createLitForm,
  crossField,
  email,
  field,
  MdyFormController,
  minLength,
  required,
  serverValidator,
} from "@modyra/lit/adapter";
import { mountMdyDevtools } from "@modyra/core/devtools";
import { defineMdyElements } from "@modyra/lit/ui";
import { html, LitElement, nothing } from "lit";

// Simulated availability endpoint. The abort signal cancels the request
// when a newer keystroke supersedes the run (last-wins), so stale replies
// never land on the field.
const isUsernameTaken = (value, signal) =>
  new Promise((resolve, reject) => {
    const timer = setTimeout(() => resolve(["admin", "root"].includes(value)), 350);
    signal?.addEventListener("abort", () => {
      clearTimeout(timer);
      reject(new DOMException("aborted", "AbortError"));
    });
  });

// Registers the whole control catalog: text, textarea, number, checkbox,
// toggle, radio group, segmented, select, multiselect, slider, datepicker,
// daterange, timepicker, colors, file.
defineMdyElements();

class SignupApp extends LitElement {
  form = createLitForm(
    {
      // Debounced, cancellable availability check with a 2s timeout —
      // try "admin" or "root".
      username: field(
        "",
        [required(), minLength(3)],
        serverValidator(
          async (value, { signal }) =>
            (await isUsernameTaken(value, signal)) ? "Username is already taken" : null,
          { debounceMs: 300, timeoutMs: 2000 },
        ),
      ),
      name: field("", [required(), minLength(2)]),
      email: field("", [required(), email()]),
      password: field("", [required(), minLength(8)]),
      confirm: field("", [required()]),
    },
    {
      validators: [
        crossField(["confirm"], (v) =>
          v.password === v.confirm ? null : "Passwords do not match"),
      ],
      history: { debounceMs: 300 },
      // The password never touches storage.
      draft: { key: "signup-stackblitz-lit", exclude: ["password", "confirm"] },
    },
  );

  // Re-render on the state this template reads outside <mdy-text-field>.
  tracker = new MdyFormController(this, [
    this.form.state.canSubmit,
    this.form.canUndo,
    this.form.canRedo,
    this.form.f.username.pending,
  ]);

  // A second, standalone form exercising every element of the catalog.
  gallery = createLitForm({
    topic: field(null, [required()]),
    plan: field("free"),
    billing: field("monthly"),
    channels: field([]),
    teamSize: field(5),
    budget: field(null),
    startDate: field(null),
    trial: field(null),
    standup: field(null),
    brand: field("#3366ff"),
    notifications: field(true),
    terms: field(false, [required()]),
    notes: field(""),
    attachments: field(null),
  });

  createRenderRoot() { return this; } // light DOM: the theme applies

  firstUpdated() {
    this._disposeDevtools = mountMdyDevtools(this.form, this.querySelector("#devtools"));
  }
  disconnectedCallback() {
    super.disconnectedCallback();
    this._disposeDevtools?.();
  }

  #submit = (e) => {
    e.preventDefault();
    void this.form.submit(async (value) => {
      // Returned errors are shown on the matching fields until edited.
      if (value.email === "taken@example.com") {
        return [{ path: "email", kind: "server", message: "This email is already registered" }];
      }
      console.log("submitted", value);
    });
  };

  render() {
    return html`
      <main style="max-width:30rem;margin:2rem auto;display:grid;gap:1rem">
        <h1>Modyra × Lit</h1>
        <p>Try username <code>admin</code> for a cancellable server check, <code>taken@example.com</code> for a server error. Reload mid-typing: the draft survives.</p>
        <form class="mdy-form" @submit=${this.#submit}>
          <mdy-text-field label="Username" .field=${this.form.f.username}></mdy-text-field>
          ${this.form.f.username.pending()
            ? html`<div class="mdy-supporting-text" role="status">checking…</div>`
            : nothing}
          <mdy-text-field label="Name" .field=${this.form.f.name}></mdy-text-field>
          <mdy-text-field label="Email" type="email" .field=${this.form.f.email}></mdy-text-field>
          <mdy-text-field label="Password" type="password" .field=${this.form.f.password}></mdy-text-field>
          <mdy-text-field label="Confirm password" type="password" .field=${this.form.f.confirm}></mdy-text-field>
          <div style="display:flex;gap:.5rem">
            <button type="submit" ?disabled=${!this.form.state.canSubmit()}>Sign up</button>
            <button type="button" ?disabled=${!this.form.canUndo()} @click=${() => this.form.undo()}>Undo</button>
            <button type="button" ?disabled=${!this.form.canRedo()} @click=${() => this.form.redo()}>Redo</button>
          </div>
        </form>
        <div id="devtools"></div>

        <h2>Control catalog</h2>
        <form class="mdy-form" style="display:grid;gap:1rem">
          <mdy-select-field label="Topic" placeholder="Pick one…"
            .field=${this.gallery.f.topic}
            .options=${[
        { value: "sales", label: "Sales" },
        { value: "support", label: "Support" },
      ]}></mdy-select-field>
          <mdy-radio-group-field label="Plan"
            .field=${this.gallery.f.plan}
            .options=${[
        { value: "free", label: "Free" },
        { value: "pro", label: "Pro" },
      ]}></mdy-radio-group-field>
          <mdy-segmented-field label="Billing"
            .field=${this.gallery.f.billing}
            .options=${[
        { value: "monthly", label: "Monthly" },
        { value: "yearly", label: "Yearly" },
      ]}></mdy-segmented-field>
          <mdy-multiselect-field label="Channels"
            .field=${this.gallery.f.channels}
            .options=${[
        { value: "mail", label: "Email" },
        { value: "sms", label: "SMS" },
        { value: "push", label: "Push" },
      ]}></mdy-multiselect-field>
          <mdy-slider-field label="Team size" min="1" max="50"
            .field=${this.gallery.f.teamSize}></mdy-slider-field>
          <mdy-number-field label="Budget" min="0" step="100"
            .field=${this.gallery.f.budget}></mdy-number-field>
          <mdy-datepicker-field label="Start date"
            .field=${this.gallery.f.startDate}></mdy-datepicker-field>
          <mdy-daterange-field label="Trial period"
            .field=${this.gallery.f.trial}></mdy-daterange-field>
          <mdy-timepicker-field label="Daily standup"
            .field=${this.gallery.f.standup}></mdy-timepicker-field>
          <mdy-colors-field label="Brand color"
            .field=${this.gallery.f.brand}></mdy-colors-field>
          <mdy-toggle-field label="Notifications"
            .field=${this.gallery.f.notifications}></mdy-toggle-field>
          <mdy-checkbox-field label="Accept terms"
            .field=${this.gallery.f.terms}></mdy-checkbox-field>
          <mdy-textarea-field label="Notes" rows="3"
            .field=${this.gallery.f.notes}></mdy-textarea-field>
          <mdy-file-field label="Attachments" multiple
            .field=${this.gallery.f.attachments}></mdy-file-field>
        </form>
      </main>`;
  }
}
customElements.define("signup-app", SignupApp);
