// packages/react/src/widgets/text-field.ts
/**
 * The text-like kinds, drawn by one component.
 *
 * `text`, `email`, `password`, `textarea` and `number` share an anatomy and differ in what they ask
 * the platform for. Which native input that is comes from the catalogue — `controlType` — not from a
 * prop a host spells: an email field whose author forgot to say so renders as plain text and loses
 * the keyboard and the handling that go with it, silently.
 *
 * The state lives in the hook this wraps, which already holds the controller against the runtime the
 * handle owns. Nothing about the widget is decided here: the parts, their classes, their relations
 * and the element each is drawn as are the contract's answers, read through the projection.
 */
import { createElement, useId, type ReactElement, type ReactNode } from "react";
import { MDY_WIDGET_CONTRACTS } from "@modyra/widgets";
import type { MdyFieldHandle } from "@modyra/core";
import { useMdyTextField } from "./field.js";
import { partProps, type MdyDeclaredPart } from "./part.js";

/** The kinds this one component draws. */
export type MdyTextLikeKind = "text" | "email" | "password" | "textarea" | "number";

/** Which element each kind's control is, where the catalogue says something other than an input. */
const TAG_FOR_ELEMENT: Readonly<Record<string, string>> = Object.freeze({ textarea: "textarea" });

export interface MdyTextFieldProps<TValue extends string | number | null> {
  readonly field: MdyFieldHandle<TValue>;
  readonly kind?: MdyTextLikeKind;
  readonly label?: string;
  /**
   * Stable identity for this widget's parts.
   *
   * Optional here and required in the Vue components, and the difference is not an inconsistency:
   * React has `useId`, which produces an identity that survives a re-render and matches between
   * server and client. A host with its own scheme still passes one.
   */
  readonly widgetId?: string;
}

export function MdyTextField<TValue extends string | number | null>(
  props: MdyTextFieldProps<TValue>,
): ReactElement {
  const kind = props.kind ?? "text";
  const contract = MDY_WIDGET_CONTRACTS[kind];
  const declared = contract.parts as Readonly<Record<string, MdyDeclaredPart | undefined>>;
  const generated = useId();
  const widgetId = props.widgetId ?? `mdy-${generated.replace(/:/g, "")}`;

  const api = useMdyTextField<TValue>(props.field, {
    widgetId,
    // From the catalogue, not from a prop: `controlType` is what the contract says a kind's native
    // input is, and a renderer spelling it here would be a second statement of it — the one that
    // stops moving when the declaration does.
    inputType: contract.controlType,
  });

  const parts = api.view.parts as Readonly<Record<string, Parameters<typeof partProps>[0]>>;
  const classesOf = (part: string): string => declared[part]?.classes.join(" ") ?? "";
  const children: ReactNode[] = [];

  // The projection names this part `input`, carries the id, the `for` that points at it, the native
  // input the kind declares, the name a submit reads and every constraint attribute. Rebuilding any
  // of that here would be a second answer to a question already answered — the first version of this
  // file did exactly that and drew an email field with no `type` and no ARIA at all.
  if (props.label !== undefined && props.label !== "") {
    children.push(createElement("label", partProps(parts["label"], { key: "label" }), props.label));
  }

  const controlNode = contract.structure.nodes.find((node) => node.part === "control");
  children.push(createElement("div", { key: "wrapper", className: classesOf("inputWrapper") },
    createElement(TAG_FOR_ELEMENT[String(controlNode?.element)] ?? "input", partProps(parts["input"], {
      key: "control",
      className: classesOf("control"),
      value: (props.field.value() ?? "") as string,
      onChange: (event: { readonly target: { readonly value: string } }) =>
        api.dispatch({ type: "input", value: event.target.value as TValue }),
      onBlur: () => api.dispatch({ type: "blur" }),
    }))));

  children.push(createElement("p", partProps(parts["description"], { key: "description" })));
  children.push(createElement("ul", partProps(parts["error"], { key: "error" })));

  return createElement("div", { className: contract.rootClasses.join(" ") }, children);
}

// packages/lit/src/components/text-field.ts
import { mdyPart } from "../mdy-part.js";
import { html, nothing, type PropertyDeclarations } from "lit";
import { type MdyFieldHandle } from "@modyra/core";
import { MDY_WIDGET_CONTRACTS, createTextFieldController, type MdyTextFieldController } from "@modyra/widgets";
import { MdyFieldElement } from "../base.js";

// ─── Text-like ────────────────────────────────────────────────────────────────

/**
 * The kinds this one element draws.
 *
 * `textarea` is text-like in the schema and is not here: it has its own element because its anatomy
 * differs, while these three share one and differ only in the native input the contract asks for.
 */
type MdyTextLikeKind = "text" | "email" | "password";

export class MdyTextFieldElement extends MdyFieldElement<string | null> {
  static override properties: PropertyDeclarations = {
    kind: { type: String },
    type: { type: String },
    placeholder: { type: String },
    autocomplete: { type: String },
  };
  /**
   * Which text-like kind this is: `text`, `email` or `password`.
   *
   * The three share one anatomy and differ only in the native input they ask for, so one element
   * draws all three — and naming the kind is what lets the contract answer that difference. A host
   * that names none gets `text`, which is what it got before this property existed.
   */
  declare kind: MdyTextLikeKind;
  declare type: string;
  declare placeholder: string;
  declare autocomplete: string;
  /**
   * What the base resolves anatomy from, and it stays `text` on purpose.
   *
   * The three kinds this element draws share one anatomy — same parts, same classes — so every
   * answer the base takes from the catalogue is the same for all of them. Widening this would move
   * a published type to say something no rendering depends on; `kind` above carries the difference
   * that is real, which is the native input.
   */
  protected override readonly widgetKind = "text" as const;
  private fieldController?: MdyTextFieldController<string | null>;

  constructor() {
    super();
    this.kind = "text";
    // Empty rather than "text": empty means *nothing was said*, and what a kind's native input
    // should be is the contract's answer. Written as a default here it would be a second statement
    // of it — the one that stops moving when the declaration does.
    this.type = "";
    this.placeholder = "";
    this.autocomplete = "";
  }

  /**
   * The native input this control asks for: what the host said, or what the kind declares.
   *
   * The explicit property stays an override, because a host may have a reason the catalogue does not
   * know. What changes is the *default*: unset, an email field used to render `type="text"` and lose
   * the keyboard and the affordance that go with it, silently and for as long as nobody looked.
   */
  private get inputType(): string {
    return this.type !== "" ? this.type : MDY_WIDGET_CONTRACTS[this.kind].controlType ?? "text";
  }

  override connectedCallback(): void {
    super.connectedCallback();
    const handle = this.field;
    if (!handle || this.fieldController) return;
    this.fieldController = createTextFieldController({
      widgetId: this.fieldId,
      handle,
      inputType: this.inputType,
      kind: this.widgetKind,
      autocomplete: this.autocomplete,
      supportingText: this.declared(() => this.supportingWords()),
    });
  }

  override disconnectedCallback(): void {
    this.fieldController?.destroy();
    this.fieldController = undefined;
    super.disconnectedCallback();
  }

  protected override renderControl(handle: MdyFieldHandle<string | null>): unknown {
    return html`<input
      id=${this.fieldId}
      type=${this.inputType}
      placeholder=${this.placeholder}
      autocomplete=${this.autocomplete || nothing}
      .value=${handle.value() ?? ""}
      ?disabled=${handle.disabled()}
      ?readonly=${handle.readonly()}
      aria-readonly=${handle.readonly() ? "true" : nothing}
      ${mdyPart(this.controlPart(handle))}
      @input=${(e: Event) => {
        const value = (e.target as HTMLInputElement).value;
        if (this.fieldController) {
          this.fieldController.dispatch({ type: "input", value });
        } else {
          handle.set(value);
          handle.markAsDirty();
        }
      }}
      @blur=${() =>
        this.fieldController
          ? this.fieldController.dispatch({ type: "blur" })
          : handle.markAsTouched()}
    />`;
  }
}
