// packages/solid/src/widgets/field.ts
/**
 * Solid primitive for the Modyra headless primitive field controller.
 */

import type { MdyFieldHandle } from "@modyra/core";
import {
  createFieldController,
  type MdyFieldControllerOptions,
  type MdyFieldIntent,
  type MdyFieldState,
  type MdyWidgetViewContract,
} from "@modyra/widgets";
import { getOwner, onCleanup } from "solid-js";

import { solidReactivity } from "../index.js";
import { executeSolidCommands } from "./runtime.js";

export type UseMdyFieldOptions<TValue> = Omit<
  MdyFieldControllerOptions<TValue>,
  "handle"
>;

export interface MdySolidFieldApi<TValue> {
  readonly state: MdyFieldState<TValue>;
  readonly view: MdyWidgetViewContract;
  dispatch(intent: MdyFieldIntent<TValue>): void;
  setValue(value: TValue): void;
  setReadonly(readonly: boolean): void;
  destroy(): void;
}

export function useMdyField<TValue>(
  handle: MdyFieldHandle<TValue>,
  options: UseMdyFieldOptions<TValue>,
): MdySolidFieldApi<TValue> {
  const reactivity = solidReactivity();
  const controller = createFieldController({ ...options, handle }, reactivity);

  const stateSig = reactivity.signal(controller.state());
  const viewSig = reactivity.signal(controller.view());

  const effectRef = reactivity.effect(() => {
    stateSig.set(controller.state());
    viewSig.set(controller.view());
  });

  if (getOwner() !== null) {
    onCleanup(() => {
      effectRef.destroy();
      controller.destroy();
    });
  }

  const dispatch = (intent: MdyFieldIntent<TValue>) => {
    executeSolidCommands(
      controller.dispatch(intent),
      () => undefined,
      {
        setOpen: () => undefined, // no overlay in this control
        onTouched: () => handle.markAsTouched(),
        onDirty: () => handle.markAsDirty(),
      },
    );
  };

  return {
    get state() {
      return stateSig();
    },
    get view() {
      return viewSig();
    },
    dispatch,
    setValue(value) {
      controller.setValue(value);
    },
    setReadonly(readonly) {
      controller.setReadonly(readonly);
    },
    destroy: controller.destroy,
  };
}

// packages/react/src/widgets/field.ts
/**
 * React hook for the Modyra headless primitive field controller.
 */

import { useCallback, useEffect, useMemo, useState } from "react";
import type { MdyFieldHandle } from "@modyra/core";
import { observerFor } from "@modyra/core";
import {
  createFieldController,
  type MdyFieldControllerOptions,
  type MdyFieldIntent,
  type MdyFieldState,
  type MdyWidgetViewContract,
} from "@modyra/widgets";

import { useMdyCommandQueue } from "./runtime.js";

export type UseMdyFieldOptions<TValue> = Omit<
  MdyFieldControllerOptions<TValue>,
  "handle"
>;

export interface MdyReactFieldApi<TValue> {
  readonly state: MdyFieldState<TValue>;
  readonly view: MdyWidgetViewContract;
  dispatch(intent: MdyFieldIntent<TValue>): void;
  setValue(value: TValue): void;
  setReadonly(readonly: boolean): void;
  destroy(): void;
}

export function useMdyField<TValue>(
  handle: MdyFieldHandle<TValue>,
  options: UseMdyFieldOptions<TValue>,
): MdyReactFieldApi<TValue> {
  const reactivity = useMemo(() => observerFor(handle), [handle]);

  const controller = useMemo(
    () => createFieldController({ ...options, handle }, reactivity),
    // Recreate only when the identity of options/handle changes.
    [options, handle, reactivity],
  );

  const { execute } = useMdyCommandQueue(
    () => undefined,
    {
      setOpen: () => undefined, // no overlay in this control
      onTouched: () => handle.markAsTouched(),
      onDirty: () => handle.markAsDirty(),
    },
  );

  const [, setVersion] = useState(0);

  useEffect(() => {
    const ref = reactivity.effect(() => {
      controller.state();
      controller.view();
      setVersion((v) => v + 1);
    });
    return () => {
      ref.destroy();
      controller.destroy();
    };
  }, [controller, reactivity]);

  const dispatch = useCallback(
    (intent: MdyFieldIntent<TValue>) => {
      execute(controller.dispatch(intent));
    },
    [controller, execute],
  );

  const setValue = useCallback(
    (value: TValue) => controller.setValue(value),
    [controller],
  );

  const setReadonly = useCallback(
    (readonly: boolean) => controller.setReadonly(readonly),
    [controller],
  );

  return {
    state: controller.state(),
    view: controller.view(),
    dispatch,
    setValue,
    setReadonly,
    destroy: controller.destroy,
  };
}
