// packages/solid/src/widgets/select.ts
/**
 * Solid primitive for the Modyra headless select controller.
 */

import type { MdySelectOption } from "@modyra/core";
import {
  createSelectController,
  type MdySelectController,
  type MdySelectControllerOptions,
  type MdySelectIntent,
  type MdySelectState,
} from "@modyra/widgets";
import { getOwner, onCleanup } from "solid-js";

import { solidReactivity } from "../reactivity.js";

export interface UseMdySelectOptions<TValue>
  extends Omit<MdySelectControllerOptions<TValue>, "onChange"> {
  readonly onChange?: (value: TValue | null) => void;
}

export interface MdySolidSelectApi<TValue> {
  readonly state: Readonly<MdySelectState<TValue>>;
  readonly view: ReturnType<MdySelectController<TValue>["view"]>;
  dispatch(intent: MdySelectIntent): readonly import("@modyra/widgets").MdyUiCommand[];
  setValue(value: TValue | null): void;
  setOptions(options: readonly MdySelectOption<TValue>[]): void;
}

/**
 * Solid primitive that creates a reactive headless select controller.
 *
 * State and view are exposed as getters over Solid signals — read them
 * inside a `createMemo`/`createEffect`/JSX expression to track natively.
 */
export function useMdySelect<TValue>(
  options: UseMdySelectOptions<TValue>,
): MdySolidSelectApi<TValue> {
  const reactivity = solidReactivity();
  const controller = createSelectController(options, reactivity);

  const stateSig = reactivity.signal(controller.state());
  const viewSig = reactivity.signal(controller.view());

  const effectRef = reactivity.effect(() => {
    stateSig.set(controller.state());
    viewSig.set(controller.view());
  });

  if (getOwner() !== null) {
    onCleanup(() => {
      effectRef.destroy();
      controller.destroy();
    });
  }

  return {
    get state(): Readonly<MdySelectState<TValue>> {
      return stateSig();
    },
    get view(): ReturnType<MdySelectController<TValue>["view"]> {
      return viewSig();
    },
    dispatch(intent) {
      return controller.dispatch(intent);
    },
    setValue(value) {
      controller.setValue(value);
    },
    setOptions(options) {
      controller.setOptions(options);
    },
  };
}

// packages/react/src/widgets/select.ts
/**
 * React hook for the Modyra headless select controller.
 */

import { useCallback, useEffect, useMemo, useState } from "react";
import type { MdySelectOption } from "@modyra/core";
import { vanillaReactivity } from "@modyra/core";
import {
  createSelectController,
  type MdySelectController,
  type MdySelectControllerOptions,
  type MdySelectIntent,
  type MdySelectState,
} from "@modyra/widgets";

import {
  useMdyCommandQueue,
  type MdyElementLookup,
  type MdyReactCommandHandlers,
} from "./runtime.js";

export interface UseMdySelectOptions<TValue>
  extends Omit<MdySelectControllerOptions<TValue>, "onChange"> {
  readonly onChange?: (value: TValue | null) => void;
}

export interface MdySelectApi<TValue> {
  readonly state: MdySelectState<TValue>;
  readonly view: ReturnType<MdySelectController<TValue>["view"]>;
  readonly dispatch: (intent: MdySelectIntent) => void;
  readonly setValue: (value: TValue | null) => void;
  readonly setOptions: (options: readonly MdySelectOption<TValue>[]) => void;
}

/**
 * React hook that creates and drives a headless select controller.
 *
 * The component re-renders on every controller state change. Commands are
 * flushed after the DOM commit via the React runtime.
 */
export function useMdySelect<TValue>(
  options: UseMdySelectOptions<TValue>,
  lookup: MdyElementLookup,
  handlers: MdyReactCommandHandlers,
): MdySelectApi<TValue> {
  const reactivity = useMemo(() => vanillaReactivity(), []);
  const controller = useMemo(
    () => createSelectController(options, reactivity),
    // Recreate only when the identity of options changes; callers should
    // memoize options or use a stable key.
    [options],
  );

  const { execute } = useMdyCommandQueue(lookup, handlers);

  const [, setVersion] = useState(0);

  useEffect(() => {
    const ref = reactivity.effect(() => {
      controller.state();
      controller.view();
      setVersion((v) => v + 1);
    });
    return () => {
      ref.destroy();
      controller.destroy();
    };
  }, [controller, reactivity]);

  const dispatch = useCallback(
    (intent: MdySelectIntent) => {
      execute(controller.dispatch(intent));
    },
    [controller, execute],
  );

  const setValue = useCallback(
    (value: TValue | null) => controller.setValue(value),
    [controller],
  );

  const setOptions = useCallback(
    (opts: readonly MdySelectOption<TValue>[]) => controller.setOptions(opts),
    [controller],
  );

  return {
    state: controller.state(),
    view: controller.view(),
    dispatch,
    setValue,
    setOptions,
  };
}
