// packages/lit/src/widget-runtime/select-adapter.ts
/**
 * Lit adapter for the Modyra headless select controller.
 *
 * Wraps the controller, triggers Lit re-renders when its signals change,
 * and executes commands via the Lit runtime.
 */

import type { MdySelectOption } from "@modyra/core";
import { observerFor } from "@modyra/core";
import {
  createSelectFieldController,
  type MdySelectFieldController,
  type MdySelectFieldControllerOptions,
  type MdySelectIntent,
  type MdySelectState,
} from "@modyra/widgets";
import type { LitElement } from "lit";

import {
  executeLitCommands,
  type MdyElementLookup,
  type MdyLitCommandHandlers,
} from "./widget-runtime.js";

/**
 * What this adapter needs, which is now what the field controller needs.
 *
 * `onChange` is gone with the standalone controller: the field controller holds the handle and
 * writes through it, so a caller supplying its own writer would be a second thing owning the value.
 */
export type MdyLitSelectAdapterOptions<TValue> = MdySelectFieldControllerOptions<TValue>;

export class MdyLitSelectAdapter<TValue = unknown> {
  private readonly host: LitElement;
  private readonly controller: MdySelectFieldController<TValue>;
  private readonly lookup: MdyElementLookup;
  private handlers: MdyLitCommandHandlers = {
    setOpen: () => undefined, // replaced by the host element
  };

  constructor(
    host: LitElement,
    options: MdyLitSelectAdapterOptions<TValue>,
    lookup: MdyElementLookup,
  ) {
    this.host = host;
    this.lookup = lookup;
    // The field controller, which holds the handle and reads it, rather than the standalone one
    // driven by setters. The setters are not less typing to skip: they are a window between a value
    // changing anywhere else — a draft restored, a server correction, a cross-field rule — and
    // somebody in this file remembering to push it in.
    // Observed through the runtime that owns the handle, never a fresh one. Two instances of the
    // same factory are two different owners, and the second is refused the first's signals at
    // runtime — a complaint on the way past, and a widget that renders once and then ignores every
    // change made anywhere else.
    this.controller = createSelectFieldController(options, observerFor(options.handle));
  }

  get state(): MdySelectState<TValue> {
    return this.controller.state();
  }

  get view(): ReturnType<MdySelectFieldController<TValue>["view"]> {
    return this.controller.view();
  }

  dispatch(intent: MdySelectIntent): void {
    const commands = this.controller.dispatch(intent);
    executeLitCommands(this.host, commands, this.lookup, this.handlers);
  }


  setOptions(options: readonly MdySelectOption<TValue>[]): void {
    this.controller.setOptions(options);
  }

  setOpen(open: boolean): void {
    this.controller.setOpen(open);
  }


  setReadonly(readonly: boolean): void {
    this.controller.setReadonly(readonly);
  }

  /** Which of the field's descriptions is on screen, so the trigger names one that exists. */
  setPopupRendered(rendered: boolean): void {
    this.controller.setPopupRendered(rendered);
  }

  setDescribedBy(next: { errorsVisible?: boolean; descriptionVisible?: boolean }): void {
    this.controller.setDescribedBy(next);
  }


  setLoading(loading: boolean): void {
    this.controller.setLoading(loading);
  }

  connectHandlers(handlers: MdyLitCommandHandlers): void {
    this.handlers = handlers;
  }

  destroy(): void {
    this.controller.destroy();
  }
}

// packages/angular/src/lib/widget-runtime/select-adapter.ts
/**
 * Angular adapter for the Modyra headless select controller.
 *
 * Bridges the framework-agnostic controller with Angular-specific command
 * execution and signal integration. The host component creates an instance,
 * feeds it DOM refs and callbacks, and reads the reactive view contract.
 */

import {
  computed,
  ElementRef,
  Injector,
  Signal,
} from "@angular/core";
import type { MdySelectOption } from "@modyra/core";
import { getFieldHandleOwner } from "@modyra/core";
import {
  createSelectFieldController,
  type MdySelectFieldController,
  type MdySelectFieldControllerOptions,
  type MdySelectIntent,
  type MdySelectState,
} from "@modyra/widgets";
import { angularReactivity } from "../core/reactivity-angular";

import {
  MdyAngularCommandHandlers,
  MdyWidgetRuntime,
} from "./widget-runtime";

/**
 * What this adapter needs, which is what the field controller needs.
 *
 * `onChange` is gone with the standalone controller: the field controller holds the handle and
 * writes through it, so a caller supplying its own writer would be a second thing owning the value.
 */
export type MdyAngularSelectAdapterOptions<TValue> = MdySelectFieldControllerOptions<TValue>;

export class MdyAngularSelectAdapter<TValue = string> {
  private readonly controller: MdySelectFieldController<TValue>;
  private readonly runtime: MdyWidgetRuntime;

  /** Reactive Angular signal wrapping the controller state. */
  readonly state: Signal<MdySelectState<TValue>>;

  /** Reactive Angular signal wrapping the view/ARIA contract. */
  readonly view: Signal<ReturnType<MdySelectFieldController<TValue>["view"]>>;

  /** Current open state, useful for binding to the overlay panel. */
  readonly open: Signal<boolean>;

  /** Registry of part element refs. */
  private readonly elements = new Map<string, ElementRef<HTMLElement>>();

  /** Registry of item element refs keyed by `part:key`. */
  private readonly itemElements = new Map<string, ElementRef<HTMLElement>>();

  /** Callbacks to the host component. */
  private handlers: MdyAngularCommandHandlers = { setOpen: () => { /* no-op until the host registers handlers */ } };

  constructor(
    options: MdyAngularSelectAdapterOptions<TValue>,
    runtime: MdyWidgetRuntime,
    injector: Injector,
  ) {
    this.runtime = runtime;

    // The runtime that owns the handle, and only a fresh one where nothing owns it yet.
    //
    // `angularReactivity` returns a new instance on every call, so building one here handed the
    // controller a second owner with the same name — and a runtime is refused the signals of one it
    // does not own. What that costs is not the complaint: it is a widget that renders once and then
    // ignores every change made anywhere else, which is what a field handle exists to deliver.
    //
    // The fallback stays Angular's rather than the shared default: a control in this package needs
    // this framework's scheduling, and `observerFor` would hand back a vanilla runtime whose signals
    // an Angular template cannot see.
    const owner = getFieldHandleOwner(options.handle);
    this.controller = createSelectFieldController(options, owner ?? angularReactivity(injector));

    // Bridge Modyra signals to Angular signals so templates can read them
    // idiomatically.
    this.state = computed(() => this.controller.state());
    this.view = computed(() => this.controller.view());
    this.open = computed(() => this.state().open);
  }

  /** Register a part element ref. */
  registerPart(name: string, ref: ElementRef<HTMLElement>): void {
    this.elements.set(name, ref);
  }

  /** Register an item element ref (e.g. an option). */
  registerItem(part: string, key: string, ref: ElementRef<HTMLElement>): void {
    this.itemElements.set(`${part}:${key}`, ref);
  }

  /** Connect host callbacks for command execution. */
  connectHandlers(handlers: MdyAngularCommandHandlers): void {
    this.handlers = handlers;
  }

  /** Dispatch an intent and execute the resulting commands. */
  dispatch(intent: MdySelectIntent): void {
    const commands = this.controller.dispatch(intent);
    this.runtime.execute(
      commands,
      this.elements,
      this.lookupItem.bind(this),
      this.handlers,
    );
  }

  /** Replace the option list. */
  setOptions(options: readonly MdySelectOption<TValue>[]): void {
    this.controller.setOptions(options);
  }

  /** Update the open state programmatically without emitting commands. */
  setOpen(open: boolean): void {
    this.controller.setOpen(open);
  }

  /** Update the readonly state. */
  setReadonly(readonly: boolean): void {
    this.controller.setReadonly(readonly);
  }

  /** Which of the two texts under the field the trigger describes itself by. */
  setDescribedBy(shown: { readonly errorsVisible?: boolean; readonly descriptionVisible?: boolean }): void {
    this.controller.setDescribedBy(shown);
  }

  /** Whether the panel's contents are in the document — this renderer builds them on open. */
  setPopupRendered(rendered: boolean): void {
    this.controller.setPopupRendered(rendered);
  }

  /** Update the loading state. */
  setLoading(loading: boolean): void {
    this.controller.setLoading(loading);
  }

  /** Release resources. */
  destroy(): void {
    this.controller.destroy();
  }

  private lookupItem(part: string, key: string): ElementRef<HTMLElement> | undefined {
    return this.itemElements.get(`${part}:${key}`);
  }
}
