// examples/stackblitz-solid/src/main.jsx
// Signup form demo: schema-defined validators, cross-field password check,
// draft persistence (reload the page mid-typing), undo/redo history, a
// cancellable server-side username check and a simulated server error on
// submit. The devtools panel at the bottom shows the live engine state;
// sensitive fields (password) are masked automatically.
//
// Unlike the React/Preact examples, field handles are read directly as
// accessors inside JSX (`handle.value()`) — Solid's compiler wraps each
// such binding in its own fine-grained update, so there is no
// useMdyField-style hook or whole-component re-render here at all.
import "@modyra/styles/material.css";
import { render } from "solid-js/web";
import { onMount } from "solid-js";
import {
  createSolidForm, crossField, email, field, minLength, required,
  serverValidator,
} from "@modyra/solid";
import { mountMdyDevtools } from "@modyra/core/devtools";

// Simulated availability endpoint. The abort signal cancels the request
// when a newer keystroke supersedes the run (last-wins), so stale replies
// never land on the field.
const isUsernameTaken = (value, signal) =>
  new Promise((resolve, reject) => {
    const timer = setTimeout(() => resolve(["admin", "root"].includes(value)), 350);
    signal?.addEventListener("abort", () => {
      clearTimeout(timer);
      reject(new DOMException("aborted", "AbortError"));
    });
  });

function TextField(props) {
  const { label, handle, type = "text" } = props;
  return (
    <div class={`mdy-renderer mdy-renderer--text${handle.touched() ? " mdy-renderer--touched" : ""}`}>
      <label class="mdy-label">
        {label}
        {/* required() marks the field, so the star and aria stay in sync */}
        {handle.required() && <span class="mdy-label__required" aria-hidden="true">*</span>}
      </label>
      <div class="mdy-input-wrapper">
        <input
          type={type}
          value={handle.value() ?? ""}
          aria-invalid={!handle.valid()}
          aria-required={handle.required()}
          onInput={(e) => handle.set(e.target.value)}
          onBlur={handle.markAsTouched}
        />
      </div>
      {/* Async validators keep the field pending until the run settles */}
      {handle.pending() && (
        <div class="mdy-supporting-text" role="status">checking…</div>
      )}
      {handle.touched() && handle.errors().length > 0 && (
        <ul class="mdy-control__errors" role="alert">
          {handle.errors().map((er) => <li class="mdy-control__error">{er.message}</li>)}
        </ul>
      )}
    </div>
  );
}

function Signup() {
  const form = createSolidForm(
    {
      // Debounced, cancellable availability check with a 2s timeout —
      // try "admin" or "root".
      username: field(
        "",
        [required(), minLength(3)],
        serverValidator(
          async (value, { signal }) =>
            (await isUsernameTaken(value, signal)) ? "Username is already taken" : null,
          { debounceMs: 300, timeoutMs: 2000 },
        ),
      ),
      name: field("", [required(), minLength(2)]),
      email: field("", [required(), email()]),
      password: field("", [required(), minLength(8)]),
      confirm: field("", [required()]),
    },
    {
      // Cross-field rules see the whole typed value and attribute their
      // error to the involved fields.
      validators: [
        crossField(["confirm"], (v) =>
          v.password === v.confirm ? null : "Passwords do not match"),
      ],
      // Value snapshots for undo/redo; keystrokes are batched.
      history: { debounceMs: 300 },
      // Autosaved to localStorage, restored on reload, cleared on submit.
      // The password never touches storage.
      draft: { key: "signup-stackblitz-solid", exclude: ["password", "confirm"] },
    },
  );

  let devtools;
  onMount(() => mountMdyDevtools(form, devtools));

  const submit = (e) => {
    e.preventDefault();
    void form.submit(async (value) => {
      // Returned errors are shown on the matching fields until edited.
      if (value.email === "taken@example.com") {
        return [{ path: "email", kind: "server", message: "This email is already registered" }];
      }
      console.log("submitted", value);
    });
  };

  return (
    <main style={{ "max-width": "30rem", margin: "2rem auto", display: "grid", gap: "1rem" }}>
      <h1>Modyra × Solid</h1>
      <p>Try username <code>admin</code> for a cancellable server check, <code>taken@example.com</code> for a server error. Reload mid-typing: the draft survives.</p>
      <form class="mdy-form" onSubmit={submit}>
        <TextField label="Username" handle={form.f.username} />
        <TextField label="Name" handle={form.f.name} />
        <TextField label="Email" handle={form.f.email} type="email" />
        <TextField label="Password" handle={form.f.password} type="password" />
        <TextField label="Confirm password" handle={form.f.confirm} type="password" />
        <div style={{ display: "flex", gap: ".5rem" }}>
          <button type="submit" disabled={!form.state.canSubmit()}>Sign up</button>
          <button type="button" disabled={!form.canUndo()} onClick={() => form.undo()}>Undo</button>
          <button type="button" disabled={!form.canRedo()} onClick={() => form.redo()}>Redo</button>
        </div>
      </form>
      <div ref={devtools}></div>
    </main>
  );
}
render(() => <Signup />, document.getElementById("app"));

// examples/stackblitz-react/src/main.jsx
// Signup form demo: schema-defined validators, cross-field password check,
// draft persistence (reload the page mid-typing), undo/redo history, a
// cancellable server-side username check and a simulated server error on
// submit. The devtools panel at the bottom shows the live engine state;
// sensitive fields (password) are masked automatically.
import "@modyra/styles/material.css";
import { createRoot } from "react-dom/client";
import { useEffect, useMemo, useRef, useSyncExternalStore } from "react";
import {
  createStore, crossField, email, field, minLength, required,
  serverValidator, useMdyField, useMdyForm,
} from "@modyra/react";
import { mountMdyDevtools } from "@modyra/core/devtools";

// Simulated availability endpoint. The abort signal cancels the request
// when a newer keystroke supersedes the run (last-wins), so stale replies
// never land on the field.
const isUsernameTaken = (value, signal) =>
  new Promise((resolve, reject) => {
    const timer = setTimeout(() => resolve(["admin", "root"].includes(value)), 350);
    signal?.addEventListener("abort", () => {
      clearTimeout(timer);
      reject(new DOMException("aborted", "AbortError"));
    });
  });

function TextField({ label, handle, type = "text" }) {
  const f = useMdyField(handle);
  const showErrors = f.touched && f.errors.length > 0;
  return (
    <div className={`mdy-renderer mdy-renderer--text${f.touched ? " mdy-renderer--touched" : ""}`}>
      <label className="mdy-label">
        {label}
        {handle.required() && <span className="mdy-label__required" aria-hidden="true">*</span>}
      </label>
      <div className="mdy-input-wrapper">
        <input
          type={type}
          value={f.value ?? ""}
          aria-invalid={!f.valid}
          aria-required={handle.required()}
          onChange={(e) => f.set(e.target.value)}
          onBlur={f.markAsTouched}
        />
      </div>
      {f.pending && (
        <div className="mdy-supporting-text" role="status">checking…</div>
      )}
      {showErrors && (
        <ul className="mdy-control__errors" role="alert">
          {f.errors.map((er) => <li className="mdy-control__error" key={er.message}>{er.message}</li>)}
        </ul>
      )}
    </div>
  );
}

function Signup() {
  const form = useMdyForm(
    () => ({
      // Debounced, cancellable availability check with a 2s timeout —
      // try "admin" or "root".
      username: field(
        "",
        [required(), minLength(3)],
        serverValidator(
          async (value, { signal }) =>
            (await isUsernameTaken(value, signal)) ? "Username is already taken" : null,
          { debounceMs: 300, timeoutMs: 2000 },
        ),
      ),
      name: field("", [required(), minLength(2)]),
      email: field("", [required(), email()]),
      password: field("", [required(), minLength(8)]),
      confirm: field("", [required()]),
    }),
    {
      validators: [
        crossField(["confirm"], (v) =>
          v.password === v.confirm ? null : "Passwords do not match"),
      ],
      history: { debounceMs: 300 },
      draft: { key: "signup-stackblitz-react", exclude: ["password", "confirm"] },
    },
  );

  useMdyField(form.f.name);
  // Buttons below read form-level state (canSubmit/canUndo/canRedo), which
  // no per-field useMdyField call above is subscribed to — without this,
  // an async validator settling on a field the parent doesn't track (e.g.
  // username) never re-renders Signup, and the buttons go stale.
  const formStore = useMemo(
    () => createStore([form.state.valid, form.state.pending, form.canUndo, form.canRedo]),
    [form],
  );
  useEffect(() => () => formStore.destroy(), [formStore]);
  useSyncExternalStore(formStore.subscribe, formStore.getSnapshot, formStore.getSnapshot);
  const devtools = useRef(null);
  useEffect(() => mountMdyDevtools(form, devtools.current), [form]);

  const submit = (e) => {
    e.preventDefault();
    void form.submit(async (value) => {
      if (value.email === "taken@example.com") {
        return [{ path: "email", kind: "server", message: "This email is already registered" }];
      }
      console.log("submitted", value);
    });
  };

  return (
    <main style={{ maxWidth: "30rem", margin: "2rem auto", display: "grid", gap: "1rem" }}>
      <h1>Modyra × React</h1>
      <p>Try username <code>admin</code> for a cancellable server check, <code>taken@example.com</code> for a server error. Reload mid-typing: the draft survives.</p>
      <form className="mdy-form" onSubmit={submit}>
        <TextField label="Username" handle={form.f.username} />
        <TextField label="Name" handle={form.f.name} />
        <TextField label="Email" handle={form.f.email} type="email" />
        <TextField label="Password" handle={form.f.password} type="password" />
        <TextField label="Confirm password" handle={form.f.confirm} type="password" />
        <div style={{ display: "flex", gap: ".5rem" }}>
          <button type="submit" disabled={!form.state.canSubmit()}>Sign up</button>
          <button type="button" disabled={!form.canUndo()} onClick={() => form.undo()}>Undo</button>
          <button type="button" disabled={!form.canRedo()} onClick={() => form.redo()}>Redo</button>
        </div>
      </form>
      <div ref={devtools}></div>
    </main>
  );
}
createRoot(document.getElementById("app")).render(<Signup />);
